# Fyrirlestraraefing 5
#### Reikningar með numpy

In [28]:
import numpy as np
a = np.array([3,2,8]) 
b = np.array([2,0,1])
c = np.array([-2,1,5])

A = np.array([[2,4,7],[3,4,8],[4,6,9]])
B = np.array([[5,5,5],[6,6,6],[7,8,9]])

dot_ab = np.dot(a, b)

Bb = np.dot(B, b)
dot_c_Bb = np.dot(c, Bb)
cnorm = 3 * np.linalg.norm(c)
part1 = dot_ab - (dot_c_Bb / cnorm)
print('a.',part1)


AT_B2 = (np.transpose(A) + B**2)
amin2b = (a - (2*b))
part2 = 2 * (AT_B2) * (amin2b)
print('\nb.',part2)

detA = np.linalg.det(A)
invA = np.linalg.inv(A)
print("\nc.",detA,'\n', invA)

x = np.linalg.solve(A, b)
print('\nd.',x)



a. 7.731619619663099

b. [[ -54  112  348]
 [ -80  160  504]
 [-112  288 1080]]

c. 10.000000000000002 
 [[-1.2  0.6  0.4]
 [ 0.5 -1.   0.5]
 [ 0.2  0.4 -0.4]]

d. [-2.   1.5  0. ]
